import numpy as np
import pandas as pd

from dosetwin.metrics import glycemic_metrics, hypo_events
from dosetwin.twin import identify as I
from dosetwin.twin import model as M
from dosetwin.twin.advisor import TwinAdvisor, risk


def _synthetic_patient(th, days=3, seed=0):
    """Data generated BY the twin model itself (self-consistency check)."""
    rng = np.random.RandomState(seed)
    T = days * 1440
    u = np.zeros(T); c = np.zeros(T); steps = np.zeros(T)
    for d in range(days):
        for mt, g in ((480, 50), (810, 80), (1260, 70)):
            t = d * 1440 + mt + rng.randint(-20, 20)
            c[t] = g; u[t] = g / 12.0 if rng.rand() > 0.15 else 0.0
        steps[d * 1440 + 1100:d * 1440 + 1140] = 110
    b = 0.01
    z = M.steady_state(th, b, 140.0)
    cgm = np.full(T, np.nan)
    for t in range(T):
        if t % 5 == 0:
            cgm[t] = z[8] + rng.normal(0, 4)
        M.step(z, th, u[t], b, c[t], steps[t], 50.0, t, False)
    return I.PatientData("synthetic", u, c, steps, cgm, b, 50.0, 12.0, 40.0)


def test_steady_state_is_steady():
    th = M.default_theta(); th[M.I_DAWN] = 0
    z = M.steady_state(th, 0.01, th[M.I_GB])
    g = M.forecast(th, z, np.zeros(600), 0.01, np.zeros(600), np.zeros(600), 50.0, 720, 600)
    assert np.max(np.abs(g - th[M.I_GB])) < 1e-6


def test_insulin_lowers_and_carbs_raise_glucose():
    th = M.default_theta()
    assert I.insulin_drop(th, 0.01, 50.0) > 0
    assert I.meal_rise(th, 0.01, 50.0, 50.0) > 0


def test_fit_recovers_glucose_dynamics_on_self_generated_data():
    true = M.default_theta(); true[M.I_LSI] = np.log(1.8); true[M.I_GB] = 125.0; true[M.I_LFC] = np.log(1.1)
    p = _synthetic_patient(true)
    start = M.default_theta()
    fr = I.fit(p, prior=start, H=180, prior_strength=5.0)
    # compare the clinically relevant responses, not raw parameters
    for f in (lambda th: I.insulin_drop(th, p.basal, p.W), lambda th: I.meal_rise(th, p.basal, p.W, 50.0, units=4.0)):
        assert abs(f(fr.theta) - f(true)) < 0.25 * abs(f(true)) + 5


def test_advisor_respects_safety_floor_and_cap():
    names = ["p0"]
    ehr = pd.DataFrame({"patient": names, "weight_kg": [50.0], "carb_ratio_g_per_u": [10.0],
                        "correction_factor_mgdl_per_u": [40.0], "basal_u_per_day": [14.4]})
    th = M.default_theta(); th[M.I_LSI] = np.log(2.0)
    adv = TwinAdvisor({"p0": th}, ehr, names)
    T = 2000
    log = {"cgm": np.full((1, T), np.nan), "bolus": np.zeros((1, T)), "carbs_logged": np.zeros((1, T)),
           "steps": np.zeros((1, T))}
    log["cgm"][0, ::5] = 120.0
    doses, traj, r, feas = adv.evaluate_doses(0, 1500, 60.0, log)
    margin = np.minimum(12 * np.arange(traj.shape[1]) / 60, 25)
    assert np.all((traj[feas] - margin).min(axis=1) >= 70)
    d = adv.meal_bolus(0, 1500, 60.0, 120.0, 0.0, log)
    std = adv.standard_dose(0, 60.0, 120.0, 0.0)
    assert 0 <= d <= max(2 * max(std, 1), std + 3)
    # more insulin => lower nadir
    assert np.all(np.diff(traj.min(axis=1)) <= 1e-9)


def test_risk_is_zero_near_112_and_symmetric_ish():
    assert risk(np.array([112.5]))[0] < 0.01
    assert risk(np.array([50.0]))[0] > risk(np.array([250.0]))[0] * 0.9


def test_metrics_and_events():
    bg = np.r_[np.full(100, 120.0), np.full(20, 60.0), np.full(100, 200.0)]
    m = glycemic_metrics(bg)
    assert abs(m["tbr_lt70"] - 20 / 220 * 100) < 1e-9
    assert hypo_events(bg) == [100]
    assert hypo_events(np.r_[np.full(10, 60.0), np.full(10, 120.0)]) == []
